apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  replicas: 2 # iki adet web sunucusu servisi ayağa kalkacak
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask # yaka etiketi: flask
    spec:
      containers:
      - name: flask-app
        image: norcholly/mikro-servis:v1 # kendi oluşturduğumuz docker imajı
        ports:
        - containerPort: 5000 # flask, 5000 portunu sever
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  type: NodePort # bu servis, dışarıdan gelen istekleri de karşılayacak
  selector:
    app: flask # yaka etiketi: flask olan pod'lara götür
  ports:
  - port: 80
    targetPort: 5000 # konteynerin portuna yönlendir ->
    nodePort: 30005 # bu porttan gelenleri <-
